### ISSUE TITLE
Whitelist IPs for known CICD providers

### ISSUE THREAD

**Issue by nquayson** [namecheap/terraform-provider-namecheap#67] opened 2022-05-21 00:53 UTC
I understand the namecheap API has this limitation. Are there any plans for whitelisting IPs of known CICD providers: Terraform Cloud, Github Actions, Azure DevOPS, AWS CodePipeline etc.

**Comment by b1ff** [comment] 2022-05-30 14:50
Hey, 
we support whitelist during API key creation in your account.

As for global whitelist - we don't have that in plan, and unfortunately in nearest future we do not consider doing that.

**Comment by tedmiston** [comment] 2022-07-25 22:39
The problem is that IPs for e.g., Terraform Cloud, are dynamic.  I do not think there is actually a whitelist one can use.  I just get failed apply after failed apply because of this issue with the Namecheap provider / API.

**Comment by lukasbach** [comment] 2023-09-24 15:18
Even for CI providers with more fixed set if IP adresses this is pretty difficult. Github provides a list of all their used IP ranges, and for github actions, it looks like they use a pool of a few thousands to ten thousands IP addresses (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses). This is kind of difficult to use with Namecheaps maximum of 20 whitelisted IP adresses. So this pretty much means this is not usable with the majority of CICD providers at the moment.

**Comment by creack** [comment] 2023-11-17 16:03
I'd be curious about this too, what is the point of having an API if it can't be used in a production setting? Is it only meant for hobbyists toying with the API from their laptops? Or is it the other extreme, meant for large enterprises (but not too large, as the max of 20 can't be increased) who can operate their own servers with dedicated IPs?

**Comment by vetal2409** [comment] 2024-02-09 12:43
Duplicate of #59

**Closed by vetal2409** 2024-02-09 12:43 UTC
